spring:
  application:
    name: hexletTypoReporter
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
