version: '3'
services:
  typo-reporter-db-postgresql:
    image: postgres:14.2-alpine3.15
    container_name: typo-reporter-db-pg
    environment:
      - POSTGRES_DB=typo-reporter
      - POSTGRES_USER=developer
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
